### ISSUE TITLE
[Suggestion] Guide Book

### ISSUE THREAD

**Issue by brachy84** [valeriotor/Beyond-The-Veil#1]
I have no idea how things work. A guide book would help. Preferably Patchouli
Thanks

**Comment by valeriotor** [comment]
Hey there! There is a guide book already, it's called Al Azif. It's obtained when you first return from the Nether, and that's also the moment the first research in it is unlocked (simply taking it out of the creative inventory won't show any research until you do as described above).
Due to the story driven style of the mod, most researches have both some gameplay descriptive parts and some narrative parts (which I know might not be everyone's cup of tea, but that was my vision of my mod all along). Further researches unlock by progressing previous ones, as well as by doing specific actions. At times I don't tell the Player how to progress to get them to look back and find their way forwards by themselves.
Due to the spoilery content of Al Azif I also don't give the Player a way to unlock all research in creative, as I'd rather not tempt the curious.
Hope this helped!

**Comment by brachy84** [comment]
Yes, thanks. So far a really cool mod
