### ISSUE TITLE
missing texture + dumb hit boxes

### ISSUE THREAD

**Issue by Zack7292** [valeriotor/Beyond-The-Veil#7]
the memory sieve don't have any texture, plus have a ridiculously small Hit box

![Screenshot_219](https://user-images.githubusercontent.com/45187146/79408792-345d1d80-7f6a-11ea-92e3-588e5c417396.png)

**Comment by Zack7292** [comment]
it might be related to a mod compatibility issue, ima do a mediafire link of my pack with configs 4 u :)

**Comment by Zack7292** [comment]
here is the link: https://www.mediafire.com/file/h6y7u5ltz2zzkxm/Infex_V.0.0.007c.zip/file
be sure to use the latest version of forge and to have at least 8GB of ram, otherwise, it won't work correctly

**Comment by valeriotor** [comment]
Thanks, I am not sure exactly _why_ it happened (probably a mod conflict since it had never happened to me before), but I did find a workaround. I'm not sure on whether to do a hotfix now or to fix it in the next update which might be some way off, but I'm opting more for the second option. I'll leave the issue open for the time being. Thanks again!

**Comment by Zack7292** [comment]
your welcome, i'm actually making a modpack, so i try to find most of the bugs and i was testing around your mod and i randomly fall on this

**Comment by valeriotor** [comment]
I just uploaded v0.1.4, when you can let me know if it fixed this problem.

**Comment by Zack7292** [comment]
You fix 1/2 of it, the texture now work, but the hit box is still wack
![Screenshot_221](https://user-images.githubusercontent.com/45187146/79498434-4df87680-7ff7-11ea-9e0d-428ca7811add.png)
maybe making it the whole fountain could be better (like all the model)

**Comment by Zack7292** [comment]
the same goes with the damp canopy with the hit box

![Screenshot_223](https://user-images.githubusercontent.com/45187146/79518404-fd950f00-801e-11ea-8605-2404ff3b912e.png)

**Comment by valeriotor** [comment]
The bounding boxes must be parallelepipeds, so in the Sieve's case I had to choose between aesthetics and functionality (since the black outlines over the block were really ugly) and I went for the former, whereas for the Canopy I had to go for the full block bounding box.
That said, your complaint spurred me to search a way to detach the actual bounding box and the one we see rendered on screen. So for the Sieve's case I made it so you can actually hit/interact with almost the full block, although the outline itself is the same. (There are probably ways to make the outline perfectly fit on the block's model, though they're likely tedious and not a priority).
The tweak will drop in a later update.
